[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-pytorch"
version = "1.1.6"
description = "Federated Learning with PyTorch and Flower (Quickstart Example)"
license = {file = "LICENSE"}
dependencies = [
    "flwr[simulation]>=1.28.0",
    "flwr-datasets[vision]>=0.6.0",
    "torch==2.10.0",
    "torchvision==0.25.0",
    "pytest"
]

#[tool.uv.sources]
#torch = [
#    { index = "pytorch-cu128" },
#]
#torchvision = [
#    { index = "pytorch-cu128" },
#]

#[[tool.uv.index]]
#name = "pytorch-cu128"
#url = "https://download.pytorch.org/whl/cu128"
#explicit = true

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"
fab-format-version = 1
flwr-version-target = "1.31.0"

[tool.flwr.app.components]
serverapp = "server_app:app"
clientapp = "client_app:app"

[tool.flwr.app.config]
num-server-rounds = 2
fraction-evaluate = 1.0
local-epochs = 1
learning-rate = 0.1
batch-size = 32
save-model = false
fraction-fit = 1.0
min-available-clients = 2
algorithm = "fedavgm"
proximal-mu = 0.01
server-learning-rate = 1.0
server-momentum = 0.9
model_name = "mobilenet"

[partition]
type = "iid"         # options: iid, dirichlet, shard
alpha = 0.5          # used only for dirichlet
num_shards = 2       # used only for shard
